### ISSUE TITLE
Составить ревью инструментов обучения НС для задач классификации

### ISSUE THREAD

**Issue by owlengineer** [DarkFlink/geology_deeplearning_osll#1]
Каждый из нас пишет к этому issue комментарий в котором форматированным markdown-ом делает список фреймворков для обучения нейронных сетей, которые лучше всего подходят под решение задач классификации изображений. 

Все помним, что лучше **качество**, поэтому не стоит сюда указывать изначально не очень подходящие фреймворки. Делаем выборку из лучших найденных

- [x] Конечный результат - выбрать фреймворк, который мы будем впоследствии использовать

**ВЫБРАН PYTORCH**

Формат ревью примерно такой:
* Тулза1 - краткое описание
[ссылка на сайт\исходники](https://github.com/DarkFlink/geology_deeplearning_osll/issues/1)
[сслыка на пример(ы) использования](https://github.com/DarkFlink/geology_deeplearning_osll/issues/1)  
Оценка: насколько по вашему мнению этот фреймворк подходит, почему. Какой порог вхождения и т.п

* Тулза2 - краткое описание
[ссылка на сайт\исходники](https://github.com/DarkFlink/geology_deeplearning_osll/issues/1)
[сслыка на пример(ы) использования](https://github.com/DarkFlink/geology_deeplearning_osll/issues/1)  
Оценка: насколько по вашему мнению этот фреймворк подходит, почему. Какой порог вхождения

...

* ТулзаN - краткое описание
[ссылка на сайт\исходники](https://github.com/DarkFlink/geology_deeplearning_osll/issues/1)
[сслыка на пример(ы) использования](https://github.com/DarkFlink/geology_deeplearning_osll/issues/1)  
Оценка: насколько по вашему мнению этот фреймворк подходит, почему. Какой порог вхождения

**Comment by owlengineer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Составить ревью библиотек и инструментов обучения НС для задач классификации](https://trello.com/c/N2bXnfBC/3-%D1%81%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D1%80%D0%B5%D0%B2%D1%8C%D1%8E-%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA-%D0%B8-%D0%B8%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%B2-%D0%BE%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BD%D1%81-%D0%B4%D0%BB%D1%8F-%D0%B7%D0%B0%D0%B4%D0%B0%D1%87-%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D0%B8)

**Comment by SuperSolik** [comment]
**Pytorch** - современная библиотека машинного обучения для языка Python с открытым исходным кодом, созданная на базе Torch. Используется для решения различных задач: компьютерное зрение, обработка естественного языка.
Сайт - https://pytorch.org/
[Обзорная статься на хабре](https://habr.com/ru/post/334380/)
**Примеры**: 
-  [Репозиторий курса на степике от Samsung](https://github.com/SlinkoIgor/Neural_Networks_and_CV) - там есть примеры и для MNIST (как полносвязная так и сверточная сети), и для CIFAR10, запускать ноутбуки кому как удобно, лично мне удобнее в Google Collab, там же есть возможность выкачать код в .py-файл + не требует никакой дополнительной установки на комп, все на облаке, вычисления на GPU.
- [Репозиторий с примерами классификации изображений](https://github.com/bentrevett/pytorch-image-classification)
- [Туториалы с оф. сайта](https://pytorch.org/tutorials/), в частности по [классификации изображений на примере CIFAR10](https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html#sphx-glr-beginner-blitz-cifar10-tutorial-py)

**Оценка**: современный, удобный, не самый низкоуровневый, что повышает порог вхождения. Есть как [предобученные модели](https://www.learnopencv.com/pytorch-for-beginners-image-classification-using-pre-trained-models/), так и возможность самостоятельно конструировать архитектуру сети в виде класса, что довольно удобно. Популярный - в сети куча примеров, готовых кусков кода, статей по решению тех или иных задач. Синтаксис простой, довольно понятный и удобный.

**Comment by NikulinNikitaDev** [comment]
**ThensorFlow** – открытая программная библиотека для машинного обучения. Основной API реализован на Python.

- Сайт: https://www.tensorflow.org/

- Пример: https://www.tensorflow.org/tutorials/keras/classification

- Оценка: библиотека включает в себя реализацию множества различных алгоритмов для решения задач машинного обучения. Изначально разрабатывалась как инструмент для создания и обучения нейросетей с целью нахождения и классификации образов. Продолжает развиваться, подходит как для решения небольших задач, так и для создания больших моделей. Для работы может использоваться удобный API Keras.

**Keras** – высокоуровневая среда разработки нейронных сетей, написанная на Python. Работает поверх TensorFlow, CNTK и Theano. Была разработана для проведения быстрых экспериментов и исследований, нацелена на оперативную работу с нейросетями.

- Сайт: https://keras.io/

- Пример: https://keras.io/getting-started/sequential-model-guide/

- Оценка: предоставляет удобный и понятный API для работы с нейросетями. Основными принципами при разработке среды являлись компактность, модульность и расширяемость, поэтому позволяет без особых усилий создать и использовать простые модели, однако при работе над большими проектами могут возникнуть трудности (например, потеря производительности).

**PyTorch** – библиотека машинного обучения на языке Python, использует для вычислений возможности графического процессора.

- Сайт: https://pytorch.org/

- Пример: https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html - содержит краткое описание библиотеки, а также примеры реализации нейронных сетей и решения задачи классификации.

- Оценка: имеет вокруг себя экосистему с различными библиотеками и инструментами для работы, а также уже готовые модели. PyTorch нацелен на простоту использования, также является достаточно гибким для решения различных задач.

**Comment by didges** [comment]
**Keras** - является надстройкой над TensorFlow, а в последних версиях и вовсе стал ее частью. Значимым плюсом Keras'а является простота создания моделей, из-за чего предоставляется возможность попробовать различные инструменты для решения задачи.
Примеры:
- [Распознавание товаров на полках с помощью нейронных сетей на технологиях Keras](https://habr.com/ru/company/true_engineering/blog/416123/)
- [Как начать работу с Keras, Deep Learning и Python](https://www.reg.ru/blog/keras/) - данная статья помогает понять -"А как работать со своими данными"
- [Многозначная классификация с помощью Keras](https://www.reg.ru/blog/mnogoznachnaya-klassifikaciya-s-pomoshchyu-keras/)

**Оценка:** Keras не подойдет в тех задачах, если вам нужны какие-то сложные вещи, вроде нестандартного слоя или распараллеливания кода на несколько GPU, тогда лучше использовать TenserFlow.

**Comment by owlengineer** [comment]
**Keras** - python надстройка над TensorFlow для обучения глубоких нейронных сетей. Часто используют как для прототипирования моделей, так и для state-of-the-art исследований и промышленных задач.

* Сайт: https://keras.io/
* Примеры:
[Оф. гайды](https://keras.io/getting-started/sequential-model-guide/#sequence-classification-with-lstm)
[Гайды на сайте TF](https://www.tensorflow.org/guide/keras/train_and_evaluate)
* Оценка: API интуитивно понятный, добавление слоёв, настройка оптимизаторов, выбор модели все базовые операции делаются одним методом с говорящими аргументами. Также плюс - очень хорошая документация и бонусом идут гайды на сайте TF, в том числе на мультиклассовую классификацию свёрточными сетями. 

**PyTorch** - python фреймворк для машинного обучения. Универсальная библиотека, для классификации изображений в том числе.

* Сайт: https://pytorch.org/
* Примеры:
[Оф. гайды](https://pytorch.org/tutorials/)
[Гайд по классификации на CIFAR-10](https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html)
[Гайд по классификации на MNIST](https://www.guru99.com/pytorch-tutorial.html)

* Оценка: широкий набор дополнительных инструментов, притом официально поддерживамых, также удобный и понятный API для описания собственных а также подгрузки уже обкатанных моделей. За счёт простоты - большое коммьюнити, а это == **куча гайдов, видеоуроков, готовых решений** и относительно низкий порог вхождения. Есть удобная поддержка CUDA, параллельных вычислений на GPU - существенный плюс при больших датасетах и моделях. 

**Примечание:** хотел включить сюда **Caffe**, это фреймворк специализирующися именно на классификации изображений, который работает для этой задачи лучше чем PyTorch и Keras. Однако у него довольно сложный и специфический API и малое community.
