### ISSUE TITLE
Разобраться с задачей кластеризации

### ISSUE THREAD

**Issue by owlengineer** [DarkFlink/geology_deeplearning_osll#14]
### Задача

Необходимо сделать ревью известных алгоритмов и оценить, какой из них:

* Наиболее простой в понимании и реализации
* Имеет больше всего примеров и источников для почитать в интернете
* Работает эффективнее прочих

Поскольку задача довольно нетривиальная и материалов при первом прогоне интернета оказалось не так много как по базовым нейронным сетям, то стоит больше ориентироваться на англоязычные источники.

Что есть почитать сейчас:
[Хабр-Статья на базовое понимание кластерного анализа](https://habr.com/ru/post/228477/)
[Блиц по самоорганизующимся картам Кохонена](https://basegroup.ru/deductor/function/algorithm/kohonen)
[Блиц по самоорганизующимся картам Кохонена 2 (англ)](https://towardsdatascience.com/self-organizing-maps-ff5853a118d4)
[Курс лекций mail.ru](https://sphere.mail.ru/materials/video/) - в этом курсе много всего, но там есть лекции по анализу данных, в которых кластеризация тоже рассматривается

**Comment by owlengineer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Разобраться с задачей кластеризации](https://trello.com/c/IRVSOxXf/10-%D1%80%D0%B0%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D1%82%D1%8C%D1%81%D1%8F-%D1%81-%D0%B7%D0%B0%D0%B4%D0%B0%D1%87%D0%B5%D0%B9-%D0%BA%D0%BB%D0%B0%D1%81%D1%82%D0%B5%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8)

**Comment by didges** [comment]
Просматривая документацию [sklearn](https://scikit-learn.org/stable/auto_examples/cluster/plot_cluster_comparison.html) я нашел результаты многих алгоритмов на разных выборках.
![sphx_glr_plot_cluster_comparison_001](https://user-images.githubusercontent.com/39410991/78901834-9527ba00-7a81-11ea-8be6-8041c8f153b5.png)
Самыми адекватными по-моему мнению являются:
-  **Метод k-средних**
Алгоритм разбивает множество элементов векторного пространства на заранее известное число кластеров k. Основная идея заключается в том, что на каждой итерации перевычисляется центр масс для каждого кластера, полученного на предыдущем шаге, затем векторы разбиваются на кластеры вновь в соответствии с тем, какой из новых центров оказался ближе по выбранной метрике. Алгоритм завершается, когда на какой-то итерации не происходит изменения внутрикластерного расстояния.
K-means простой в понимании и реализации метод.
Его недостатки:
1)необходимо заранее знать количество кластеров 
2)алгоритм очень чувствителен к выбору начальных центров кластеров
Типичный пример сходимости
![K-means_convergence_to_a_local_minimum](https://user-images.githubusercontent.com/39410991/78903156-6ad6fc00-7a83-11ea-9e76-85f9eca91cdb.png)
- **AgglomerativeClustering**
Идея алгоритма состоит в том, что изначально каждый элемент является кластером, а новые кластеры создаются путем объединения более мелких кластеров. Кластеры объединяются по заданной мере расстояния, например метод ближайшего соседа, метод дальнего сосед, метод средней связи и др.
Главной особенностью алгоритма является то, что строиться общее дерево кластеров - Дендрограмма, и нам не нужно будет пересчитывать весь алгоритм если мы захотим изменить число кластеров.
Классическая Дендрограмма
![Iris_dendrogram](https://user-images.githubusercontent.com/39410991/78904962-fce00400-7a85-11ea-92cc-2cadd486de05.png)
Из недостатков я бы упомянул, что алгоритм достаточно требователен к потребляемой памяти.
-  **DBSCAN**
Идея, положенная в основу алгоритма, заключается в том, что внутри каждого кластера наблюдается типичная плотность точек, которая заметно выше, чем плотность снаружи кластера, а также плотность в областях с шумом ниже плотности любого из кластеров. Ещё точнее, что для каждой точки кластера её соседство заданного радиуса должно содержать не менее некоторого числа точек, это число точек задаётся пороговым значением.
Как выполняется алгоритм:
1)Происходит разметка точек на основные, пограничные и шумовые
2)Отсекаем шумовые точки
3)Соединяем основные точки в кластеры и добавляем пограничные элементы
Иллюстрация работы DBSCAN 
![0ba54babe162458bb9f8e004e5329cfa](https://user-images.githubusercontent.com/39410991/78912892-db384a00-7a90-11ea-82da-2d6b4790d70d.png)
DBSCAN отлично себя зарекомендовал в сегментации изображения

Что еще можно почитать:
 [Иерархическая кластеризация](https://ru.wikipedia.org/wiki/%D0%98%D0%B5%D1%80%D0%B0%D1%80%D1%85%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F_%D0%BA%D0%BB%D0%B0%D1%81%D1%82%D0%B5%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F)
[Статья на хабре про иерархическую кластеризацию](https://habr.com/ru/company/hh/blog/427477/)
[Подробнее про DBSCAN](https://habr.com/ru/post/322034/)
[Реализация алгоритма k-means (k-средних) на примере работы с пикселями(на C++)](https://habr.com/ru/post/427761/)

**Comment by SuperSolik** [comment]
В библиотеке PyTorch имеются [готовые модели](https://pytorch.org/docs/stable/torchvision/models.html#semantic-segmentation) для сегментации изображений, [примеры их использования](https://www.learnopencv.com/pytorch-for-beginners-semantic-segmentation-using-torchvision/). Из этих моделей особенно интересует **DeepLabV3** - модель от Google, вот [обзорная статья](https://towardsdatascience.com/review-deeplabv3-atrous-convolution-semantic-segmentation-6d818bfd1d74). 
**Модель можно обучить на своем датасете**. [Репозиторий со скриптами для обучения](https://github.com/msminhas93/DeepLabv3FineTuning) - в README есть ссылка на статью о том как это использовать, + в примерах модель обучается различать трещины на асфальте, что довольно схоже с тем что нам в теории надо будет делать.

Картинка работы модели из приведенного репозитория:
![sadsadasd](https://user-images.githubusercontent.com/31539612/78930985-b9998b80-7aad-11ea-855b-43bc121173d5.png)

[Оригинальная статья, если вдруг кому интересно](https://arxiv.org/abs/1706.05587)

Имеются еще две архитектуры - [U-Net](https://arxiv.org/abs/1505.04597) и [FusionNet](https://arxiv.org/abs/1612.05360), разработанные для медицины, но вполне могут использоваться для любых изображений. [Репозиторий с реализованными архитектурами и пример использования](https://github.com/GunhoChoi/Kind-PyTorch-Tutorial/tree/master/12_Semantic_Segmentation).

Начальное изображение:
![image](https://user-images.githubusercontent.com/31539612/78931127-11d08d80-7aae-11ea-8aad-996a45ce16d4.png)
Полученное:
![image](https://user-images.githubusercontent.com/31539612/78931864-3f6a0680-7aaf-11ea-860d-483880462be6.png)



[Обзорная статья про U-Net](https://towardsdatascience.com/u-net-b229b32b4a71), в конце статьи полезные ссылки.



 В целом я думаю использование нейронных сетей дает более гибкий и надежный механизм для сегментации изображений, подходит для нетипичных и сложных датасетов, а сами данные требуют понятной для понимания подготовки, которая может быть осуществлена средствами самого PyTorch.

**Comment by NikulinNikitaDev** [comment]
- **Метод k-средних** – строит заданное число кластеров, стараясь минимизировать суммарное квадратичное отклонение элементов кластера от его центра. Является одним из самых известных и наиболее популярных методов, поэтому имеет большое количество примеров. Достаточно прост в понимании и реализации. Также имеет различные улучшения и изменения (k-means++).
[Страница на вики](https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_k-%D1%81%D1%80%D0%B5%D0%B4%D0%BD%D0%B8%D1%85)
- **FOREL** – основан на идее объединения в один кластер объектов в областях их наибольшего сгущения. Также является достаточно простым в понимании, однако имеет достаточно низкую производительность, сильно зависит от выбора начального объекта. 
[Страница на вики](https://ru.wikipedia.org/wiki/%D0%90%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC%D1%8B_%D1%81%D0%B5%D0%BC%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B0_FOREL)
- **Самоорганизующаяся карта Кохонена** – представляет собой нейронную сеть, выполняющую задачу кластеризации и визуализации. Сложнее предыдущих алгоритмов, однако имеет устойчивость к зашумлённым данным, а также быстрое обучение.
[Страница на вики](https://ru.wikipedia.org/wiki/%D0%A1%D0%B0%D0%BC%D0%BE%D0%BE%D1%80%D0%B3%D0%B0%D0%BD%D0%B8%D0%B7%D1%83%D1%8E%D1%89%D0%B0%D1%8F%D1%81%D1%8F_%D0%BA%D0%B0%D1%80%D1%82%D0%B0_%D0%9A%D0%BE%D1%85%D0%BE%D0%BD%D0%B5%D0%BD%D0%B0)
[Статья с описанием](https://basegroup.ru/community/articles/som)
- **Иерархическая кластеризация** – совокупность алгоритмов, которые создают дерево вложенных кластеров. Делятся на два основных типа: разбивающие крупные кластеры на более мелкие (divisive) и объединяющие мелкие кластеры в более крупные (agglomerative). Данный подход является как плюсом (не нужно задавать количество кластеров), так и минусом (дополнительная работа по разбиению или объединению).
[Страница на вики](https://ru.wikipedia.org/wiki/%D0%98%D0%B5%D1%80%D0%B0%D1%80%D1%85%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F_%D0%BA%D0%BB%D0%B0%D1%81%D1%82%D0%B5%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F)
