### ISSUE TITLE
Найти и\или закодить примеры обучения НС на MNIST датасете + графики

### ISSUE THREAD

**Issue by owlengineer** [DarkFlink/geology_deeplearning_osll#2]
Мы хотим получить этим заданием скрипт на питоне, который:

* Обучает НС на датасете MNIST (найти в интернете и разобраться как он работает, можно построчно прогнать код, что он делает)
Лучше самому запрогать пример, так лучше понимаешь последовательность и суть происходящего

* Выводит графики аккуратности (accuracy) (часто говорят точность, это метрика того, насколько хороша сеть для решения нашей задачи) на обучающих данных (training data accuracy) и валидационных (validation data accuracy).

**Comment by owlengineer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Найти и\или закодить примеры обучения НС на MNIST датасете + графики](https://trello.com/c/Tszy9OC0/5-%D0%BD%D0%B0%D0%B9%D1%82%D0%B8-%D0%B8-%D0%B8%D0%BB%D0%B8-%D0%B7%D0%B0%D0%BA%D0%BE%D0%B4%D0%B8%D1%82%D1%8C-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D1%8B-%D0%BE%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BD%D1%81-%D0%BD%D0%B0-mnist-%D0%B4%D0%B0%D1%82%D0%B0%D1%81%D0%B5%D1%82%D0%B5-%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%BA%D0%B8)

**Comment by owlengineer** [comment]
Графики точности и ошибки

![image](https://user-images.githubusercontent.com/31723721/78052441-c7e9f800-7387-11ea-90ad-9141beac259a.png)

![train_loss_history](https://user-images.githubusercontent.com/31723721/78053171-e0a6dd80-7388-11ea-916b-6fcf892e7cec.png)

**Comment by NikulinNikitaDev** [comment]
#7 mnist example
