### ISSUE TITLE
Найти датасеты по геологической теме

### ISSUE THREAD

**Issue by owlengineer** [DarkFlink/geology_deeplearning_osll#21]
## Задача

Необходимо найти датасеты, которые по теме похожи на нашу, т.е картинки слоёв грунтовых пород. Искать стоит на платформах вроде
* [kaggle](https://www.kaggle.com/)
* [google research](https://research.google/)
* [CrowdAnalytix](https://www.crowdanalytix.com/community)
* [DrivenData](https://www.drivendata.co/open-source.html)
...

Есть ещё много подобных ресурсов, но они в целом хуже чем kaggle и GR.

Соответственно результат - список датасетов, с кратким описанием, сколько картинок, качество картинок и т.п + ссылка

**Comment by owlengineer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Найти датасеты по геологической теме](https://trello.com/c/QcUm2gbJ/11-%D0%BD%D0%B0%D0%B9%D1%82%D0%B8-%D0%B4%D0%B0%D1%82%D0%B0%D1%81%D0%B5%D1%82%D1%8B-%D0%BF%D0%BE-%D0%B3%D0%B5%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B9-%D1%82%D0%B5%D0%BC%D0%B5)

**Comment by owlengineer** [comment]
# Синопсис

Найти датасеты конкретно со снимками "стаканов" из грунтовых пород не удалось. Есть несколько интересных датасетов, которые могут бть использованы, чтобы потренироваться. Один из датасетов показал возможность использования сейсмоданных, даже без картинок слоёв. В этом случае сейсмоданные сами должны быть картинками, тогда можно проводить сегментацию. Тем не менее, тогда нужно заранее знать, смотря на волновые данные где какой слой находится.

# Датасеты

### Детекция соли на сейсмоданных 

Этот датасет наиболее близок к нашей задаче.

[Сегментация слоёв соли на сейсмоданных](https://www.kaggle.com/c/tgs-salt-identification-challenge/data) - есть набор картинок 101x101, которые представляют собой данные волновой активности. Зная, как ведёт себя соль при облучении волнами нужно правильно определять на картинках слои соли.

К данному датасету есть очень хороший [кернел](https://www.kaggle.com/jesperdramsch/intro-to-seismic-salt-and-how-to-geophysics). Что полезного там есть:
- Ссылки на визуализацию SEGY файлов, чтобы можно было преобразовать их в картинки для сегментации
- Готовое решение для датасета + хорошие пояснения и интро в геологическую тему

### Сегментация типов поверхности по изображениям земли

[Датасет](https://www.kaggle.com/tpapp157/earth-terrain-height-and-segmentation-map-images) представляет собой набор картинок поверхности земли вида сверху 512х512. Этот датасет можно применить, чтобы потренироваться в сегментации изображений.

**Comment by SuperSolik** [comment]
# Датасеты
[Большое количество официальных американских наборов данных по геологической тематике](https://catalog.data.gov/dataset?metadata_type=non-geospatial&tags=geothermal&res_format=ZIP)
## Поперечные сканы
По ссылке выше был найден следующий [датасет](https://catalog.data.gov/dataset/roosevelt-hot-springs-utah-forge-deep-well-58-32-mu-esw1-core-data-79354), скачанный по первой ссылке архив содержит картинки следующего типа:
![image](https://user-images.githubusercontent.com/31539612/79492441-b1e76300-8028-11ea-96d2-25dfb0b58cf2.png)
По все видимости это поперечные сканы "стаканов" пород. Продольные снимки отсутствуют в данном архиве отсутствуют.

**Comment by didges** [comment]
Сколько не искал ничего лучше, чем соревнование [TGS Salt Identification Challenge](https://www.kaggle.com/c/tgs-salt-identification-challenge/data) на kaggle не нашел, я считаю это отличный датасет так как есть подробные решения данной задачи

**Comment by NikulinNikitaDev** [comment]
В процессе поиска было просмотрено несколько источников. В результате не удалось найти ничего подходящего под наши требования (разве что вышеупомянутый [TGS Salt Identification Challenge](https://www.kaggle.com/c/tgs-salt-identification-challenge/data)). Наиболее подходящими считаю следующие данные, содержащие фотографии керна:
[Mountain Home Well Core and Drill Site Photos](https://gdr.openei.org/submissions/289)
[Kimama Well Core and Drill Site Photos](https://gdr.openei.org/submissions/290)
Однако по представленным ссылкам не было найдено каких-либо результатов обработки этих данных, т.е. нейросеть по ним обучить не получится.
Помимо Kaggle и Google Research поиск вёлся на следующих сайтах:
[Geothermal Data Repository](https://gdr.openei.org/home)
[U.S. Government’s open data](https://www.data.gov/)
[Data.world](https://data.world/)
