### ISSUE TITLE
Определиться с новыми задачами

### ISSUE THREAD

**Issue by owlengineer** [DarkFlink/geology_deeplearning_osll#26]
# Задача

Цель - найти\придумать задачу, которая могла бы подготовить нас к решению геологической задачи. Один из пунктов этой задачи - сегментация изображений на некоторые классы. Соответственно, мы можем разобраться, как сегментировать другие датасеты картинок на разные классы, и это поможет нам быстрее сделать какой-то прототип, когда появится размеченный датасет с картинками почв.

Таким образом результат - это N датасетов для многоклассовой сегментации с кратким описанием: 
* размер датасета (в т.ч вес на диске)
* какие классы в нем есть и сколько
* по своему усмотрению, если что-то посчитаете важной информацией

**Важно!** Если находите не относящуюся к теме сегментации, но по вашему мнению интересную задачу - прикладывайте её в ответ и кратко опишите почему решили её добавить.

**Comment by owlengineer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Определиться с новыми задачами](https://trello.com/c/18K2m5Mb/16-%D0%BE%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B8%D1%82%D1%8C%D1%81%D1%8F-%D1%81-%D0%BD%D0%BE%D0%B2%D1%8B%D0%BC%D0%B8-%D0%B7%D0%B0%D0%B4%D0%B0%D1%87%D0%B0%D0%BC%D0%B8)

**Comment by owlengineer** [comment]
* TGS Salt Challange. Ранее упоминавшийся датасет для сегментации месторождений соли на кратинках 101х101. Бинарная сегментация, т.е есть соль, нет соли.

* [Lunar Dataset](https://www.kaggle.com/romainpessia/artificial-lunar-rocky-landscape-dataset). Есть набор картинок 10000 шт. которые представляют собой снимки лунных ландшафтов и маски для сегментации. Всего 3 класса: небо, малые валуны и большие валуны, всё остальное - поверхность луны.

**Comment by NikulinNikitaDev** [comment]
- COCO – Common Objects in Context

Содержит различные изображения для сегментации. 118К изображений для тренировочных данных и 5К для тестовых. 80 классов. Самый большой размер данных для скачивания – 18Гб.
[Ссылка](http://cocodataset.org/#home)

- Pascal VOC data sets

Изображения для сегментации. 20 классов. Данные содержат 7К изображений. 2Гб.
[Ссылка на датасет](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/index.html#data)
[Статья](https://d2l.ai/chapter_computer-vision/semantic-segmentation-and-dataset.html)

- Earth Terrain, Height, and Segmentation Map Images

Датасет с фотографиями поверхности земли, содержит 5К изображений размером 512x512. Сегментация на 7 классов.
[Ссылка](https://www.kaggle.com/tpapp157/earth-terrain-height-and-segmentation-map-images)
